ocu_only_map = {
    ('sin empleo', None, 'otro', None): [
        "sin ocupación", "enfermo",
        "es como ama de casa porque se dedica a cuidar a sus papas",
        "esta en cama", "discapacidad", "iniciara estudios",
        "cuida a un niño especial", "no ejerce por su discapacidad",
        "discapacitado no camina síndrome",
        "no trabaja por su discapacidad", "no hace nada", "sin estudiar",
        "en cama", "en terapia", "mayor de edad enferma",
        "no estudia por problemas económicos", "capacidad diferente",
        "está enferma en casa", "estar en la casa",
        "tiene discapacidad", "cuida a su mama", "incapacitado",
        "servir a dios", "se encuentra en cama", "sin actividad actual",
        "esperando entrar a la universidad", "solo con ayuda de gobierno",
        "esta enferma y no puede trabajar",
        "sin estudiar no acredito el examen", "realmente nada", "ninguna",
        'estudiante universitario'
    ],

    ('otro', None, 'otro', None): [
        "descansó", "esta de vacaciones", "semana de descanso", "incapacidad",
        "esta incapacitada por nacimiento de su bb", "lo atropellaron",
        "incapacidad por salud", "trabaja pero anda de vacaciones",
        "incapacidad por operación",
        "si esta trabajando pero anda de vacaciones", "incapacidad temporal",
        "faltó al trabajo", "ritualista", "esta incapacitado", "misionera",
        "trabajos eventuales", "no especifico", "otro", "empleo eventual",
        "trabaja por temporadas", "n.p", "sobrino", "trabajo", "eventual",
        "trabaja con su esposo", "ama de casa y trabaja",
        "no quiso dar información", "estudia y trabaja",
        "trabaja y estudia", "estudiante y trabaja",
    ],

    ('empleada(o) u obrera(o)', None, 'comercio', None): [
        "ventas", "vendedor", "velador", "gerente", "cobrador",
        "afanador", "tienda de abarrotes", "negocio", "en un comercio",
        "paquetero de soriana", "paquetero",
        "tienda de abarrotes del papa le ayuda a atenderla",
        "paquetería de aurrera", "acomoda en el mercado de abastos",
        "recolector de aluminio", "trabaja con su tío",
        "trabaja en una tienda de abarrotes", "pasteleria", "demostradora",
        "gasolinero", "venta de material para reciclar",
        "venta de pollo", "ayudante de la ferretería de su papa",
        "de paquetero", "elabora comida para venta",
        "paquetería voluntaria de supermercado", "vendedor de reciclaje",
        "almacén", "repostera", "artesano", "despachador", "reclutamiento",
        "encargada", "negocios para tienda", "encargado", "jefe almacén",
        "cosméticos", "tienda autoservicio", "empleada pastelería",
    ],

    ('empleada(o) u obrera(o)', None, 'servicios', None): [
        "técnico", "recolección de residuos", "doctor (a)", "vende comida",
        "instructor de gimnasio", "escolta", "musico", "músico", "fotógrafo",
        "repartidor", "servicio de limpieza", "mantenimiento", "cajero (a)",
        "salud", "mesera", "intendente", "trabaja en su casa", "limpieza",
        "trabaja en un restaurante", "ayudante de mecánico",
        "lavador de autos", "repartidor de comidas", "lava carros",
        "servicio de limpieza en vivienda", "taquero", "tapicero",
        "hogar", "lava autos", "reparación de lavadoras",
        "trabaja servicio de limpieza", "programador",
        "técnico en mantenimiento", "beisbolista", "abogado",
        "limpieza de solares o jardines", "reparador de aparatos",
        "prefecta", "niñera", "enfermera doméstica", "enfermera", "cocinera",
        "inversionista", "asistente de servicios",
        "técnico  en refrigeración", "ayudante taller", "contador",
        "filarmónico", "trabajo en casa", "almacén fiscal", "climas",
        "oficinista", "servicio tecnico", "ojalatero", "mecánico automotriz",
        "técnico en refrigeración", "mecánico electricista", "limpiavidrios",
        "fotógrafa", "técnico en computadoras", "parrillero",
        "tec mantenimiento", "técnico en mantenimiento climas",
        "jugador de beisbol",
        "trabaja en casa  como ayudante  pero no siempre va es un trabajo expontaneo",
        "da clases de apoyo del inea", "mesero", "lava salas", "nana",
        "trabajadora social", "trabajo eventual limpieza", "escolta personal",
        "canta en un grupo", "talachero", "mantenimiento a residencias",
        "conserje", "servidumbre", "da clases de ingles", "enfermero",
        "sistemas", "inversiones", "técnico electrodoméstico",
        "criminólogo", "finanzas", "financiera", "jefe de meseros",
        "multifuncional"
    ],

    ('empleada(o) u obrera(o)', None, 'industria manufacturera', None): [
        "operario", "supervisor", "tornero", "fabrica", "medicina",
        "operaria", "pemex", "operador general", "operador de maquinaria",
        "empleado tornero", "obrero", "taller torno", "ingeniero analista",
        "pintura automotriz",
        "fabrica de costales", "jefe de personal"
    ],

    ('trabajador(a) por cuenta propia', None, 'comercio', None): [
        "tiene negocio en su hogar", "pepenador", "pepenador de pet",
        "recolector de pet", "recolecta papel y botellas", "comerciante",
        "ventas por catalogo"
    ],

    ('trabajador(a) por cuenta propia', None, 'construcción', None): [
        "pintor de casas", "trabaja en su domicilio. es carpintero",
        "soldador independiente", "instalador de cantera independiente",
        "soldador por su cuenta", "azulejero", "yesero",
        "peón de albañil",
    ],

    ('empleada(o) u obrera(o)', None, 'construcción', None): [
        "ayudante de su papa albañil", "se dedica a la construcción",
        "aluminífero", "constructora"
    ],

    ('empleada(o) u obrera(o)', None, 'agricultura y ganadería', None): [
        "caporal de rancho", "agricultor", "fumigador", "ganadero",
        "trabaja en un rancho"
    ],

    ('empleada(o) u obrera(o)', None, 'gobierno', None): [
        "militar", "policía", "brigadista", "servidor público", "soldado",
        "tránsito", "general"
    ],

    ('trabajador(a) por cuenta propia', None, 'servicios', None): [
        "coach", "sastre", "costurera", "barbero", "jardinería",
        "realiza varios trabajos por su cuenta para la casa",
        "trabaja por su cuenta en lo que salga", "cuida animales",
        "dentista", "trabaja en su casa de mecánico",
    ],

    ('Es pensionada(o) o jubilada(o)', None, 'otro', None): [
        "tramitando pensión", "pemsdionados", "jubilado",
        "el habitante es jubilado pero trabaja el fin de semana como musico",
        "pencionado", "lo van a pensionar", "esta tramitando la pensión"
    ],

    ('ama de casa', None, 'otro', None): [
        "en hogar", "labores del hogar"
    ],

    ('patrón(a) o empleador(a)', None, 'transporte y comunicaciones', None): [
        "negocio camiones volteo"
    ],

    ('patrón(a) o empleador(a)', None, 'servicios', None): [
        "maneja la guardería en su domicilio", "socio accionista"
    ],

    ('empleada(o) u obrera(o)', None, 'transporte y comunicaciones', None): [
        "operador de auto"
    ],

    ('patrón(a) o empleador(a)', None, 'comercio', None): [
        "negocios"
    ],
}

sect_map = {
    'vende cartón y plastico': 'comercio',
    'soldador': 'industria manufacturera',
    'mecanico automotriz': 'servicios',
    'vigilante': 'servicios',
    'operaria': 'industria manufacturera',
    'en fábrica': 'industria manufacturera',
    'cocinera': 'servicios',
    'frabrica': 'industria manufacturera',
    'velador': 'comercio',
    'cargador': 'industria manufacturera',
    'jardinero': 'servicios',
    'maestra': 'servicios',
    'artesanias': 'comercio',
    'empleeado en un local': 'comercio',
    'hotel': 'servicios',
    'gas': 'comercio',
    'artesano': 'comercio',
    'local de artesanias': 'comercio',
    'gasolineria': 'comercio',
    'local en los cavazos': 'comercio',
    'arte': 'servicios',
    'deposito de cerveza': 'comercio',
    'intendente': 'servicios',
    'muebles': 'comercio',
    'gasolinero': 'comercio',
    'oxxo': 'comercio',
    'seguridad': 'servicios',
    'pesca': 'comercio',
    'restaurante de la familia': 'servicios',
    'tienda de artículos para el hoga': 'comercio',
    'mecano': 'servicios',
    'alimentos': 'servicios',
    'vidriería': 'comercio',
    'vendedor ambulante': 'comercio',
    'catedrático universidad': 'servicios',
    'educación privada': 'servicios',
    'fabricación de plásticos': 'industria manufacturera',
    'sector salud': 'servicios',
    'obrero': 'industria manufacturera',
    'trailero': 'transporte y comunicaciones',
    'técnico mtto': 'servicios',
    'realiza práctica profesional en hospital materno': 'servicios',
    'mantenimiento': 'servicios',
    'cuida una quinta': 'servicios',
    'taller': 'servicios',
    'medicina': 'servicios',
    'eventual (particular)': 'otro',
    'entretenimiento': 'servicios',
    'escuela religiosa': 'servicios',
    'trabajos varios para el hogar': 'servicios',
    'limpieza': 'servicios',
    'administrativo': 'servicios',
    'comunicacion': 'transporte y comunicaciones',
    'repartidor': 'servicios',
    'financiero': 'servicios',
    'administracion': 'servicios',
    'hospital': 'servicios',
    'laminas': 'comercio',
    'pastelera': 'comercio',
    'hojalata y lamina': 'comercio',
    'director': 'servicios',
    'ventas': 'comercio',
    'dentista': 'servicios',
    'automotriz': 'industria manufacturera',
    'reciclaje': 'comercio',
    'no comento': 'otro',
    'panadero': 'comercio',
    'restaurante-alimentos': 'servicios',
    'bancario': 'servicios',
    'costuras': 'servicios',
    'educativo': 'servicios',
    'tienda': 'comercio',
    'tecnología': 'comercio',
    'licenciada': 'servicios',
    'técnico en refrigeración': 'servicios',
    'manufactura': 'industria manufacturera',
    'inspector': 'servicios',
    'casa': 'construcción',
    'trabaja en una pedrera': 'industria manufacturera',
    'taller mecanico': 'servicios',
    'tortonero': 'transporte y comunicaciones',
    'contadora': 'servicios',
    'montacargista': 'comercio',
    'montacarguista': 'comercio',
    'supervisor': 'industria manufacturera',
    'química': 'servicios',
    'mozo': 'comercio',
    'jardineria': 'servicios',
    'mecanico': 'servicios',
    'tornero': 'industria manufacturera',
    'doméstica': 'servicios',
    'taquero': 'servicios',
    'vende fruta preparada': 'comercio',
    'staff trabaja en un grupo musical': 'servicios',
    'chófer en casa': 'transporte y comunicaciones',
    'intendente de kinder': 'servicios',
    'imprenta': 'servicios',
    'químicos': 'servicios',
    'lic en diseño gráfico y artes visuales': 'servicios',
    'enfermeria': 'servicios',
    'mantenimiento técnico': 'servicios',
    'tortilleria': 'comercio',
    'mecanica': 'servicios',
    'domestico': 'servicios',
    'cuida niños': 'servicios',
    'diseños': 'servicios',
    'mecánico': 'servicios',
    'valores': 'servicios',
    'taller soldadora': 'industria manufacturera',
    'mesero': 'servicios',
    'musico': 'servicios',
    'vendedor': 'comercio',
    'logística': 'transporte y comunicaciones',
    'jugador de fútbol': 'servicios',
    'metal mecánica': 'industria manufacturera',
    'turismo': 'servicios',
    'venta de zapatos por catálogo': 'comercio',
    'agua y drenaje': 'gobierno',
    'jefe área': 'servicios',
    'repartidor en motocicleta': 'servicios',
    'limpieza en casa': 'servicios',
    'limpieza de casas': 'servicios',
    'limpieza en casas': 'servicios',
    'lava camiones': 'servicios',
    'pinta casas': 'construcción',
    'ayudante': 'otro',
    'metalúrgica': 'industria manufacturera',
    'oficina': 'servicios',
    'maestro': 'servicios',
    'eventual haciendo comida': 'servicios',
    'carpintero': 'servicios',
    'prestamos hipotecaria': 'servicios',
    'estilista': 'servicios',
    'mercado': 'comercio',
    'productor musical': 'servicios',
    'empacadora': 'comercio',
    'diseño': 'servicios',
    'no informó': 'otro',
    'municipio': 'gobierno',
    'no sabe': 'otro',
    'enfermera': 'servicios',
    'tacos': 'servicios',
    'tacos mañaneros': 'servicios',
    'compra fierro metal': 'comercio',
    'limpieza de oficinas': 'servicios',
    'electricidad y plomeria': 'construcción',
    'electronica': 'industria manufacturera',
    'impermeabiliza': 'construcción',
    'asesora de ventas': 'comercio',
    'clinica': 'servicios',
    'empleado': 'otro',
    'fabrica ensamblador': 'industria manufacturera',
    'vende en mercaditos': 'comercio',
    'cobrador': 'comercio',
    'docente': 'servicios',
    'gimnasia': 'servicios',
    'diseño industrial': 'industria manufacturera',
    'servicio dependencias escolares': 'servicios',
    'maestra de pilates': 'servicios',
    'carpintería': 'construcción',
    'recicladora': 'comercio',
    'siderurgica': 'industria manufacturera',
    'mercadoctenia': 'comercio',
    'carniceria': 'comercio',
    'madedero': 'comercio',
    'taler': 'servicios',
    'imss': 'servicios',
    'salud/farmacia': 'comercio',
    'abogada': 'servicios',
    'notificadora': 'servicios',
    'abogado': 'servicios',
    'viajes': 'servicios',
    'oficinistas': 'servicios',
    'cfe': 'transporte y comunicaciones',
    'ind papelera': 'industria manufacturera',
    'fábrica de tu unicel': 'industria manufacturera',
    'textiles': 'industria manufacturera',
    'químico': 'servicios',
    'administración de proyectos': 'servicios',
    'carnes empaque': 'comercio',
    'fumigación': 'servicios',
    'fábrica de chocolate': 'industria manufacturera',
    'empacadora de carnes': 'comercio',
    'se hace. chocolates': 'industria manufacturera',
    'empaque de carne': 'comercio',
    'bodega': 'comercio',
    'vende comida': 'comercio',
    'la costeña (chiles, fríjoles etc)': 'industria manufacturera',
    'empresa que se dedica a empaque': 'industria manufacturera',
    'afanador': 'comercio',
    'fabrica de chocolate': 'industria manufacturera',
    'guardia de seguridad': 'servicios',
    'cuida su ganado': 'agricultura y ganadería',
    'secretaria': 'servicios',
    'el casa': 'otro',
    'separador de metales': 'industria manufacturera',
    'recolección de residuos': 'servicios',
    'recolección de metales': 'comercio',
    'recolección de metal': 'comercio',
    'costurera': 'servicios',
    'tienda propia': 'comercio',
    'labor solcial': 'servicios',
    'entrenador de deportes': 'servicios',
    'venta de ropa': 'comercio',
    'cerrejeria': 'servicios',
    'prepa privada': 'servicios',
    'bocinas estereos': 'comercio',
    'trabaja en su camion de carga': 'transporte y comunicaciones',
    'aceros': 'industria manufacturera',
    'mercado rodante': 'comercio',
    'hace tortillas de harina': 'comercio',
    'mesero en restaurante': 'servicios',
    'repara aparatos eléctricos': 'servicios',
    'es demostradora': 'comercio',
    'maestro de preparatoria': 'servicios',
    'servicio social': 'otro',
    'coser uniformes': 'industria manufacturera',
    'fuerz civil': 'gobierno',
    'liverpool': 'comercio',
    'telmex': 'transporte y comunicaciones',
    'carnicero': 'comercio',
    'empresa': 'servicios',
    'carpinteria': 'construcción',
    'da clases de beisbol': 'servicios',
    'iniciativa privada': 'otro',
    'diseñador grafico': 'servicios',
    'telecomunicaciones': 'transporte y comunicaciones',
    'fabrica oficina': 'industria manufacturera',
    'en los medios de comunicación': 'transporte y comunicaciones',
    'administracio n': 'servicios',
    'hacen pinturas': 'industria manufacturera',
    'despacho': 'servicios',
    'personal': 'otro',
    'diseño grafico': 'servicios',
    'operario': 'industria manufacturera',
    'jugeteria': 'comercio',
    'recepcionista': 'servicios',
    'reciclajes': 'comercio',
    'instalacion de fibra optica': 'servicios',
    'comidas': 'comercio',
    'oficinista': 'servicios',
    'almacen': 'comercio',
    'descanso y no realizo ningun viaje': 'otro',
    'trabajadora doméstica': 'servicios',
    'belleza': 'servicios',
    'repara aparatos': 'servicios',
    'va por gasolina': 'otro',
    'trabajo en casa': 'otro',
    'industria metalúrgica': 'industria manufacturera',
    'industria farmacéutica': 'industria manufacturera',
    'industria gastronómica': 'servicios',
    'industria quimica': 'industria manufacturera',
    'taller de torno': 'industria manufacturera',
    'alimentación y bebidas': 'servicios',
    'asesor': 'servicios',
    'bienes raíces': 'servicios',
    'industria': 'industria manufacturera',
    'industria fundición': 'industria manufacturera',
    'inge. sistemas': 'servicios',
    'investigacón': 'servicios',
    'guarderia': 'servicios',
    'guarderia pemex': 'servicios',
    'banco': 'servicios',
    'trabajan plástico': 'industria manufacturera',
    'guardia': 'servicios',
    'vendedores': 'comercio',
    'vendedora': 'comercio',
    'alimenticia': 'industria manufacturera',
    'vende tacos': 'servicios',
    'es vendedor en el mercado de abastos de san nicolas': 'comercio',
    'trabaja en un puesto de pollos': 'comercio',
    'industria refresquera': 'industria manufacturera',
    'bienes raices': 'servicios',
    'vende ropa en los mercados': 'comercio',
    'intendencia': 'servicios',
    'taxista': 'transporte y comunicaciones',
    'energeticos': 'industria manufacturera',
    'fabrica ensamble de carros kia': 'industria manufacturera',
    'chofer': 'transporte y comunicaciones',
    'grupo energeticos planta 2': 'industria manufacturera',
    'arenas silicas': 'industria manufacturera',
    'doctor': 'servicios',
    'fabrica de escobas': 'industria manufacturera',
    'maesta': 'servicios',
    'abastecimiento industrial': 'industria manufacturera',
    'trabajos en general por su cuenta limpia maleza, albañilería etc.': 'servicios',
    'tiene taxis de renta': 'transporte y comunicaciones',
    'tesoreria de vialidad y transito': 'gobierno',
    'vende comidas': 'comercio',
    'fundidora cadereyta': 'industria manufacturera',
    'hospital de pemex': 'servicios',
    'piedrera san angel': 'industria manufacturera',
    'guarderia de pemex': 'servicios',
    'ojalatero': 'servicios',
    'enfermero': 'servicios',
    'rellenonsanitario': 'servicios',
    'mesera': 'servicios',
    'empleada domestica': 'servicios',
    'cuida rancho': 'agricultura y ganadería',
    'zapateria': 'comercio',
    'ferreteria': 'comercio',
    'autopartes': 'industria manufacturera',
    'refaccionista': 'comercio',
    'empleada en un abarrotes': 'comercio',
    'comercio ambulante': 'comercio',
    'chófer foráneo': 'transporte y comunicaciones',
    'compañía everest': 'servicios',
    'la reynera escobera': 'comercio',
    'central de autobuses': 'transporte y comunicaciones',
    'elaboración de tamales': 'comercio',
    'lic. en administración de empresas': 'servicios',
    'tienda de ropa': 'comercio',
    'centro de a tensión a clientes telefónica': 'servicios',
    'carbonera': 'industria manufacturera',
    'almacenista': 'comercio',
    'herreria': 'industria manufacturera',
    'herrero': 'industria manufacturera',
    'campo de golf': 'servicios',
    'maquila': 'industria manufacturera',
    'maquiladora': 'industria manufacturera',
    'maderera': 'comercio',
}
